"""morphological feature dimensions

Revision ID: 15a0c44e82f7
Revises: a1c9d4e77b10
Create Date: 2026-07-25 13:01:48.130058

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '15a0c44e82f7'
down_revision: str | None = 'a1c9d4e77b10'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('morphological_analyses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aspect', sa.String(length=8), nullable=True))
        batch_op.add_column(sa.Column('verb_form', sa.String(length=6), nullable=True))
        batch_op.add_column(sa.Column('voice', sa.String(length=4), nullable=True))
        batch_op.add_column(sa.Column('mood', sa.String(length=8), nullable=True))
        batch_op.add_column(sa.Column('person', sa.String(length=1), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.String(length=1), nullable=True))
        batch_op.add_column(sa.Column('grammatical_number', sa.String(length=1), nullable=True))
        batch_op.add_column(sa.Column('case_marking', sa.String(length=4), nullable=True))
        batch_op.add_column(sa.Column('definiteness', sa.String(length=8), nullable=True))
        batch_op.add_column(sa.Column('nominal_form', sa.String(length=6), nullable=True))
        batch_op.create_index('ix_analyses_search', ['pos', 'aspect', 'verb_form'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('morphological_analyses', schema=None) as batch_op:
        batch_op.drop_index('ix_analyses_search')
        batch_op.drop_column('nominal_form')
        batch_op.drop_column('definiteness')
        batch_op.drop_column('case_marking')
        batch_op.drop_column('grammatical_number')
        batch_op.drop_column('gender')
        batch_op.drop_column('person')
        batch_op.drop_column('mood')
        batch_op.drop_column('voice')
        batch_op.drop_column('verb_form')
        batch_op.drop_column('aspect')

    # ### end Alembic commands ###
