"""phase D multi-source morphology

Revision ID: 16c114e0f70e
Revises: 92255767c05f
Create Date: 2026-07-25 01:34:20.847348

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '16c114e0f70e'
down_revision: str | None = '92255767c05f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('golden_root_cases',
    sa.Column('surah_number', sa.Integer(), nullable=False),
    sa.Column('ayah_number', sa.Integer(), nullable=False),
    sa.Column('word_number', sa.Integer(), nullable=False),
    sa.Column('expected_roots', sa.String(length=120), nullable=False),
    sa.Column('citation', sa.String(length=300), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_golden_root_cases')),
    sa.UniqueConstraint('surah_number', 'ayah_number', 'word_number', name='uq_golden_position')
    )
    op.create_table('morphology_sources',
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('source_version', sa.String(length=40), nullable=True),
    sa.Column('license_note', sa.String(length=500), nullable=True),
    sa.Column('file_sha256', sa.String(length=64), nullable=True),
    sa.Column('notice', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('draft', 'imported', 'machine_generated', 'under_review', 'approved', 'published', 'disputed', 'rejected', 'deprecated', name='record_status', native_enum=False, length=32), nullable=False),
    sa.Column('confidence', sa.Enum('verified', 'high', 'medium', 'low', 'machine_only', 'disputed', name='confidence_level', native_enum=False, length=32), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_morphology_sources')),
    sa.UniqueConstraint('code', name=op.f('uq_morphology_sources_code'))
    )
    op.create_table('token_root_decisions',
    sa.Column('ayah_id', sa.Uuid(), nullable=False),
    sa.Column('word_number', sa.Integer(), nullable=False),
    sa.Column('rationale', sa.String(length=1000), nullable=False),
    sa.Column('status', sa.Enum('draft', 'imported', 'machine_generated', 'under_review', 'approved', 'published', 'disputed', 'rejected', 'deprecated', name='record_status', native_enum=False, length=32), nullable=False),
    sa.Column('proposed_by', sa.Uuid(), nullable=False),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_note', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('word_number > 0', name=op.f('ck_token_root_decisions_decision_word_number_positive')),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('fk_token_root_decisions_approved_by_users')),
    sa.ForeignKeyConstraint(['ayah_id'], ['ayahs.id'], name=op.f('fk_token_root_decisions_ayah_id_ayahs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proposed_by'], ['users.id'], name=op.f('fk_token_root_decisions_proposed_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_token_root_decisions')),
    sa.UniqueConstraint('ayah_id', 'word_number', name='uq_decision_position')
    )
    with op.batch_alter_table('token_root_decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_token_root_decisions_ayah_id'), ['ayah_id'], unique=False)

    op.create_table('tokens',
    sa.Column('ayah_id', sa.Uuid(), nullable=False),
    sa.Column('word_number', sa.Integer(), nullable=False),
    sa.Column('surface_text', sa.String(length=200), nullable=False),
    sa.Column('normalized_text', sa.String(length=200), nullable=False),
    sa.Column('char_start', sa.Integer(), nullable=False),
    sa.Column('char_end', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('char_end > char_start', name=op.f('ck_tokens_token_char_span_valid')),
    sa.CheckConstraint('word_number > 0', name=op.f('ck_tokens_token_word_number_positive')),
    sa.ForeignKeyConstraint(['ayah_id'], ['ayahs.id'], name=op.f('fk_tokens_ayah_id_ayahs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tokens')),
    sa.UniqueConstraint('ayah_id', 'word_number', name=op.f('uq_tokens_ayah_id'))
    )
    with op.batch_alter_table('tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tokens_ayah_id'), ['ayah_id'], unique=False)

    op.create_table('morphological_analyses',
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('ayah_id', sa.Uuid(), nullable=False),
    sa.Column('word_number', sa.Integer(), nullable=False),
    sa.Column('segment_number', sa.Integer(), nullable=False),
    sa.Column('token_id', sa.Uuid(), nullable=True),
    sa.Column('form_source', sa.String(length=200), nullable=False),
    sa.Column('tag', sa.String(length=16), nullable=False),
    sa.Column('features', sa.String(length=400), nullable=False),
    sa.Column('pos', sa.String(length=16), nullable=True),
    sa.Column('is_stem', sa.Boolean(), nullable=False),
    sa.Column('lemma', sa.String(length=120), nullable=True),
    sa.Column('lemma_index', sa.Integer(), nullable=True),
    sa.Column('root_id', sa.Uuid(), nullable=True),
    sa.Column('source_root_text', sa.String(length=40), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('segment_number > 0', name=op.f('ck_morphological_analyses_analysis_segment_number_positive')),
    sa.CheckConstraint('word_number > 0', name=op.f('ck_morphological_analyses_analysis_word_number_positive')),
    sa.ForeignKeyConstraint(['ayah_id'], ['ayahs.id'], name=op.f('fk_morphological_analyses_ayah_id_ayahs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['root_id'], ['roots.id'], name=op.f('fk_morphological_analyses_root_id_roots'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_id'], ['morphology_sources.id'], name=op.f('fk_morphological_analyses_source_id_morphology_sources'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['token_id'], ['tokens.id'], name=op.f('fk_morphological_analyses_token_id_tokens'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_morphological_analyses')),
    sa.UniqueConstraint('source_id', 'ayah_id', 'word_number', 'segment_number', name='uq_analysis_source_position')
    )
    with op.batch_alter_table('morphological_analyses', schema=None) as batch_op:
        batch_op.create_index('ix_analyses_position', ['ayah_id', 'word_number', 'segment_number'], unique=False)
        batch_op.create_index('ix_analyses_root', ['root_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_morphological_analyses_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_morphological_analyses_token_id'), ['token_id'], unique=False)

    op.create_table('token_root_decision_roots',
    sa.Column('decision_id', sa.Uuid(), nullable=False),
    sa.Column('root_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['token_root_decisions.id'], name=op.f('fk_token_root_decision_roots_decision_id_token_root_decisions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['root_id'], ['roots.id'], name=op.f('fk_token_root_decision_roots_root_id_roots'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('decision_id', 'root_id', name=op.f('pk_token_root_decision_roots'))
    )
    with op.batch_alter_table('root_occurrences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token_id', sa.Uuid(), nullable=True))
        # server_default ضروري: الجدول قد يحوي صفوفًا مبذورة قبل الترقية،
        # وهي فعلًا «bundle_import» حتى يُعاد اشتقاقها من التحليلات.
        batch_op.add_column(sa.Column('derivation', sa.Enum('bundle_import', 'single_source', 'source_agreement', 'human_decision', name='root_derivation', native_enum=False, length=32), nullable=False, server_default='bundle_import'))
        batch_op.create_unique_constraint('uq_occurrence_position', ['root_id', 'ayah_id', 'word_number'])
        batch_op.create_foreign_key(batch_op.f('fk_root_occurrences_token_id_tokens'), 'tokens', ['token_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('surahs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('basmala_text', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('surahs', schema=None) as batch_op:
        batch_op.drop_column('basmala_text')

    with op.batch_alter_table('root_occurrences', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_root_occurrences_token_id_tokens'), type_='foreignkey')
        batch_op.drop_constraint('uq_occurrence_position', type_='unique')
        batch_op.drop_column('derivation')
        batch_op.drop_column('token_id')

    op.drop_table('token_root_decision_roots')
    with op.batch_alter_table('morphological_analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_morphological_analyses_token_id'))
        batch_op.drop_index(batch_op.f('ix_morphological_analyses_source_id'))
        batch_op.drop_index('ix_analyses_root')
        batch_op.drop_index('ix_analyses_position')

    op.drop_table('morphological_analyses')
    with op.batch_alter_table('tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tokens_ayah_id'))

    op.drop_table('tokens')
    with op.batch_alter_table('token_root_decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_token_root_decisions_ayah_id'))

    op.drop_table('token_root_decisions')
    op.drop_table('morphology_sources')
    op.drop_table('golden_root_cases')
    # ### end Alembic commands ###
