"""refresh session rotation

Revision ID: 4535f47b9479
Revises: 15a0c44e82f7
Create Date: 2026-07-25 14:10:04.175573

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '4535f47b9479'
down_revision: str | None = '15a0c44e82f7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_sessions',
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('chain_id', sa.Uuid(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_reason', sa.String(length=60), nullable=True),
    sa.Column('replaced_by', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=200), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_sessions')),
    sa.UniqueConstraint('jti', name=op.f('uq_refresh_sessions_jti'))
    )
    with op.batch_alter_table('refresh_sessions', schema=None) as batch_op:
        batch_op.create_index('ix_refresh_sessions_chain', ['chain_id'], unique=False)
        batch_op.create_index('ix_refresh_sessions_user_active', ['user_id', 'revoked_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_refresh_sessions_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('refresh_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_sessions_user_id'))
        batch_op.drop_index('ix_refresh_sessions_user_active')
        batch_op.drop_index('ix_refresh_sessions_chain')

    op.drop_table('refresh_sessions')
    # ### end Alembic commands ###
