"""initial schema

Revision ID: 92255767c05f
Revises: 
Create Date: 2026-07-25 00:40:44.548204

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '92255767c05f'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roots',
    sa.Column('display_root', sa.String(length=40), nullable=False),
    sa.Column('normalized_root', sa.String(length=20), nullable=False),
    sa.Column('root_length', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'imported', 'machine_generated', 'under_review', 'approved', 'published', 'disputed', 'rejected', 'deprecated', name='record_status', native_enum=False, length=32), nullable=False),
    sa.Column('confidence', sa.Enum('verified', 'high', 'medium', 'low', 'machine_only', 'disputed', name='confidence_level', native_enum=False, length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('root_length between 2 and 5', name=op.f('ck_roots_root_length_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roots')),
    sa.UniqueConstraint('normalized_root', name=op.f('uq_roots_normalized_root'))
    )
    op.create_table('surahs',
    sa.Column('number', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('arabic_name', sa.String(length=80), nullable=False),
    sa.Column('revelation_type', sa.String(length=20), nullable=False),
    sa.CheckConstraint('number between 1 and 114', name=op.f('ck_surahs_surah_range')),
    sa.PrimaryKeyConstraint('number', name=op.f('pk_surahs'))
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.String(length=80), nullable=True),
    sa.Column('old_data', sa.JSON(), nullable=True),
    sa.Column('new_data', sa.JSON(), nullable=True),
    sa.Column('reason', sa.String(length=1000), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_audit_logs_actor_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_table('conflict_of_interest_declarations',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('details', sa.String(length=1000), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_conflict_of_interest_declarations_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conflict_of_interest_declarations'))
    )
    op.create_table('quran_text_versions',
    sa.Column('version_code', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('riwayah', sa.String(length=80), nullable=False),
    sa.Column('script_type', sa.String(length=40), nullable=False),
    sa.Column('counting_system', sa.String(length=40), nullable=False),
    sa.Column('source_name', sa.String(length=200), nullable=False),
    sa.Column('source_reference', sa.String(length=500), nullable=True),
    sa.Column('sha256_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('draft', 'imported', 'machine_generated', 'under_review', 'approved', 'published', 'disputed', 'rejected', 'deprecated', name='record_status', native_enum=False, length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_validated', sa.Boolean(), nullable=False),
    sa.Column('approved_by_first', sa.Uuid(), nullable=True),
    sa.Column('approved_by_second', sa.Uuid(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('activated_by', sa.Uuid(), nullable=True),
    sa.Column('activation_reason', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['activated_by'], ['users.id'], name=op.f('fk_quran_text_versions_activated_by_users')),
    sa.ForeignKeyConstraint(['approved_by_first'], ['users.id'], name=op.f('fk_quran_text_versions_approved_by_first_users')),
    sa.ForeignKeyConstraint(['approved_by_second'], ['users.id'], name=op.f('fk_quran_text_versions_approved_by_second_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quran_text_versions')),
    sa.UniqueConstraint('version_code', name=op.f('uq_quran_text_versions_version_code'))
    )
    with op.batch_alter_table('quran_text_versions', schema=None) as batch_op:
        batch_op.create_index('uq_only_one_active_version', ['is_active'], unique=True)

    op.create_table('reviewer_qualifications',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('specialty', sa.String(length=120), nullable=False),
    sa.Column('institution', sa.String(length=200), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_reviewer_qualifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reviewer_qualifications'))
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('researcher', 'linguistic_reviewer', 'sharia_reviewer', 'text_officer', 'quality_manager', 'tech_admin', 'arbitration_committee', name='user_role', native_enum=False, length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_roles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_roles')),
    sa.UniqueConstraint('user_id', 'role', name=op.f('uq_user_roles_user_id'))
    )
    op.create_table('ayahs',
    sa.Column('text_version_id', sa.Uuid(), nullable=False),
    sa.Column('surah_number', sa.Integer(), nullable=False),
    sa.Column('ayah_number', sa.Integer(), nullable=False),
    sa.Column('uthmani_text', sa.String(length=4000), nullable=False),
    sa.Column('plain_search_text', sa.String(length=4000), nullable=True),
    sa.Column('text_hash', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('ayah_number > 0', name=op.f('ck_ayahs_ayah_number_positive')),
    sa.ForeignKeyConstraint(['surah_number'], ['surahs.number'], name=op.f('fk_ayahs_surah_number_surahs')),
    sa.ForeignKeyConstraint(['text_version_id'], ['quran_text_versions.id'], name=op.f('fk_ayahs_text_version_id_quran_text_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ayahs')),
    sa.UniqueConstraint('text_version_id', 'surah_number', 'ayah_number', name=op.f('uq_ayahs_text_version_id'))
    )
    with op.batch_alter_table('ayahs', schema=None) as batch_op:
        batch_op.create_index('ix_ayahs_search', ['plain_search_text'], unique=False)

    op.create_table('root_occurrences',
    sa.Column('root_id', sa.Uuid(), nullable=False),
    sa.Column('ayah_id', sa.Uuid(), nullable=False),
    sa.Column('word_number', sa.Integer(), nullable=False),
    sa.Column('is_highlight_safe', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['ayah_id'], ['ayahs.id'], name=op.f('fk_root_occurrences_ayah_id_ayahs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['root_id'], ['roots.id'], name=op.f('fk_root_occurrences_root_id_roots'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_root_occurrences'))
    )
    with op.batch_alter_table('root_occurrences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_root_occurrences_ayah_id'), ['ayah_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_root_occurrences_root_id'), ['root_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('root_occurrences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_root_occurrences_root_id'))
        batch_op.drop_index(batch_op.f('ix_root_occurrences_ayah_id'))

    op.drop_table('root_occurrences')
    with op.batch_alter_table('ayahs', schema=None) as batch_op:
        batch_op.drop_index('ix_ayahs_search')

    op.drop_table('ayahs')
    op.drop_table('user_roles')
    op.drop_table('reviewer_qualifications')
    with op.batch_alter_table('quran_text_versions', schema=None) as batch_op:
        batch_op.drop_index('uq_only_one_active_version')

    op.drop_table('quran_text_versions')
    op.drop_table('conflict_of_interest_declarations')
    op.drop_table('audit_logs')
    op.drop_table('users')
    op.drop_table('surahs')
    op.drop_table('roots')
    # ### end Alembic commands ###
