"""phase F projects reports

Revision ID: edd086dad83a
Revises: fa87f6f8a57a
Create Date: 2026-07-25 02:03:06.847773

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'edd086dad83a'
down_revision: str | None = 'fa87f6f8a57a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('visibility', sa.Enum('private', 'internal', 'public', name='project_visibility', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('draft', 'imported', 'machine_generated', 'under_review', 'approved', 'published', 'disputed', 'rejected', 'deprecated', name='record_status', native_enum=False, length=32), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('length(title) > 0', name=op.f('ck_projects_project_title_required')),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_projects_owner_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )
    op.create_table('project_members',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('owner', 'editor', 'viewer', name='project_role', native_enum=False, length=32), nullable=False),
    sa.Column('added_by', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], name=op.f('fk_project_members_added_by_users')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_members_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_project_members_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_members')),
    sa.UniqueConstraint('project_id', 'user_id', name='uq_project_member')
    )
    with op.batch_alter_table('project_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_members_project_id'), ['project_id'], unique=False)

    op.create_table('reports',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('length(title) > 0', name=op.f('ck_reports_report_title_required')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_reports_created_by_users')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_reports_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports'))
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_project_id'), ['project_id'], unique=False)

    op.create_table('report_versions',
    sa.Column('report_id', sa.Uuid(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('content_snapshot', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('claim_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'imported', 'machine_generated', 'under_review', 'approved', 'published', 'disputed', 'rejected', 'deprecated', name='record_status', native_enum=False, length=32), nullable=False),
    sa.Column('published_by', sa.Uuid(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('change_note', sa.String(length=1000), nullable=True),
    sa.Column('supersedes_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('version_number > 0', name=op.f('ck_report_versions_report_version_positive')),
    sa.ForeignKeyConstraint(['published_by'], ['users.id'], name=op.f('fk_report_versions_published_by_users')),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], name=op.f('fk_report_versions_report_id_reports'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supersedes_id'], ['report_versions.id'], name=op.f('fk_report_versions_supersedes_id_report_versions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_report_versions')),
    sa.UniqueConstraint('report_id', 'version_number', name='uq_report_version')
    )
    with op.batch_alter_table('report_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_versions_report_id'), ['report_id'], unique=False)

    op.create_table('project_claims',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('claim_id', sa.Uuid(), nullable=False),
    sa.Column('added_by', sa.Uuid(), nullable=False),
    sa.Column('ordering', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], name=op.f('fk_project_claims_added_by_users')),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], name=op.f('fk_project_claims_claim_id_claims'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_claims_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_claims')),
    sa.UniqueConstraint('project_id', 'claim_id', name='uq_project_claim')
    )
    with op.batch_alter_table('project_claims', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_claims_claim_id'), ['claim_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_claims_project_id'), ['project_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_claims', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_claims_project_id'))
        batch_op.drop_index(batch_op.f('ix_project_claims_claim_id'))

    op.drop_table('project_claims')
    with op.batch_alter_table('report_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_versions_report_id'))

    op.drop_table('report_versions')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_project_id'))

    op.drop_table('reports')
    with op.batch_alter_table('project_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_members_project_id'))

    op.drop_table('project_members')
    op.drop_table('projects')
    # ### end Alembic commands ###
