"""phase E sources citations claims

Revision ID: fa87f6f8a57a
Revises: 16c114e0f70e
Create Date: 2026-07-25 01:58:10.090544

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'fa87f6f8a57a'
down_revision: str | None = '16c114e0f70e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_works',
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('author', sa.String(length=200), nullable=False),
    sa.Column('work_type', sa.Enum('dictionary', 'tafsir', 'grammar', 'hadith', 'qiraat', 'article', 'dataset', 'other', name='work_type', native_enum=False, length=32), nullable=False),
    sa.Column('edition', sa.String(length=200), nullable=False),
    sa.Column('publisher', sa.String(length=200), nullable=True),
    sa.Column('publication_year', sa.Integer(), nullable=True),
    sa.Column('isbn', sa.String(length=20), nullable=True),
    sa.Column('language', sa.String(length=40), nullable=False),
    sa.Column('license_note', sa.String(length=500), nullable=False),
    sa.Column('access_url', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('status', sa.Enum('draft', 'imported', 'machine_generated', 'under_review', 'approved', 'published', 'disputed', 'rejected', 'deprecated', name='record_status', native_enum=False, length=32), nullable=False),
    sa.Column('added_by', sa.Uuid(), nullable=False),
    sa.Column('verified_by', sa.Uuid(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('length(edition) > 0', name=op.f('ck_source_works_source_edition_required')),
    sa.CheckConstraint('length(license_note) > 0', name=op.f('ck_source_works_source_license_required')),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], name=op.f('fk_source_works_added_by_users')),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], name=op.f('fk_source_works_verified_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_works')),
    sa.UniqueConstraint('code', name=op.f('uq_source_works_code'))
    )
    op.create_table('citations',
    sa.Column('source_work_id', sa.Uuid(), nullable=False),
    sa.Column('locator', sa.String(length=200), nullable=False),
    sa.Column('quoted_text', sa.String(length=1000), nullable=True),
    sa.Column('paraphrase', sa.Text(), nullable=True),
    sa.Column('added_by', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('length(locator) > 0', name=op.f('ck_citations_citation_locator_required')),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], name=op.f('fk_citations_added_by_users')),
    sa.ForeignKeyConstraint(['source_work_id'], ['source_works.id'], name=op.f('fk_citations_source_work_id_source_works'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_citations')),
    sa.UniqueConstraint('source_work_id', 'locator', 'quoted_text', name='uq_citation_position')
    )
    with op.batch_alter_table('citations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_citations_source_work_id'), ['source_work_id'], unique=False)

    op.create_table('claims',
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('claim_type', sa.Enum('semantic', 'morphological', 'usage', 'comparison', name='claim_type', native_enum=False, length=32), nullable=False),
    sa.Column('subject_type', sa.Enum('root', 'lemma', 'word', 'ayah', name='claim_subject', native_enum=False, length=32), nullable=False),
    sa.Column('root_id', sa.Uuid(), nullable=True),
    sa.Column('ayah_id', sa.Uuid(), nullable=True),
    sa.Column('word_number', sa.Integer(), nullable=True),
    sa.Column('lemma', sa.String(length=120), nullable=True),
    sa.Column('status', sa.Enum('draft', 'imported', 'machine_generated', 'under_review', 'approved', 'published', 'disputed', 'rejected', 'deprecated', name='record_status', native_enum=False, length=32), nullable=False),
    sa.Column('confidence', sa.Enum('verified', 'high', 'medium', 'low', 'machine_only', 'disputed', name='confidence_level', native_enum=False, length=32), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('approved_by_first', sa.Uuid(), nullable=True),
    sa.Column('approved_by_second', sa.Uuid(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_note', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('length(statement) > 0', name=op.f('ck_claims_claim_statement_required')),
    sa.CheckConstraint('word_number is null or word_number > 0', name=op.f('ck_claims_claim_word_number_positive')),
    sa.ForeignKeyConstraint(['approved_by_first'], ['users.id'], name=op.f('fk_claims_approved_by_first_users')),
    sa.ForeignKeyConstraint(['approved_by_second'], ['users.id'], name=op.f('fk_claims_approved_by_second_users')),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_claims_author_id_users')),
    sa.ForeignKeyConstraint(['ayah_id'], ['ayahs.id'], name=op.f('fk_claims_ayah_id_ayahs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['root_id'], ['roots.id'], name=op.f('fk_claims_root_id_roots'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_claims'))
    )
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_claims_ayah_id'), ['ayah_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_claims_root_id'), ['root_id'], unique=False)

    op.create_table('claim_citations',
    sa.Column('claim_id', sa.Uuid(), nullable=False),
    sa.Column('citation_id', sa.Uuid(), nullable=False),
    sa.Column('stance', sa.Enum('supports', 'opposes', 'context', name='citation_stance', native_enum=False, length=32), nullable=False),
    sa.Column('note', sa.String(length=1000), nullable=True),
    sa.Column('added_by', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], name=op.f('fk_claim_citations_added_by_users')),
    sa.ForeignKeyConstraint(['citation_id'], ['citations.id'], name=op.f('fk_claim_citations_citation_id_citations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], name=op.f('fk_claim_citations_claim_id_claims'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_claim_citations')),
    sa.UniqueConstraint('claim_id', 'citation_id', name='uq_claim_citation')
    )
    with op.batch_alter_table('claim_citations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_claim_citations_citation_id'), ['citation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_claim_citations_claim_id'), ['claim_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('claim_citations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_claim_citations_claim_id'))
        batch_op.drop_index(batch_op.f('ix_claim_citations_citation_id'))

    op.drop_table('claim_citations')
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_claims_root_id'))
        batch_op.drop_index(batch_op.f('ix_claims_ayah_id'))

    op.drop_table('claims')
    with op.batch_alter_table('citations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_citations_source_work_id'))

    op.drop_table('citations')
    op.drop_table('source_works')
    # ### end Alembic commands ###
