"""phase G review disputes corrections

Revision ID: fbedf650a558
Revises: edd086dad83a
Create Date: 2026-07-25 02:08:26.488384

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'fbedf650a558'
down_revision: str | None = 'edd086dad83a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disputes',
    sa.Column('target_type', sa.Enum('claim', 'source_work', 'root_decision', 'report_version', name='review_target', native_enum=False, length=32), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.Column('raised_by', sa.Uuid(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('open', 'under_arbitration', 'resolved', 'withdrawn', name='dispute_status', native_enum=False, length=32), nullable=False),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('resolved_by', sa.Uuid(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('length(reason) > 0', name=op.f('ck_disputes_dispute_reason_required')),
    sa.ForeignKeyConstraint(['raised_by'], ['users.id'], name=op.f('fk_disputes_raised_by_users')),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], name=op.f('fk_disputes_resolved_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_disputes'))
    )
    with op.batch_alter_table('disputes', schema=None) as batch_op:
        batch_op.create_index('ix_dispute_target', ['target_type', 'target_id'], unique=False)

    op.create_table('review_assignments',
    sa.Column('target_type', sa.Enum('claim', 'source_work', 'root_decision', 'report_version', name='review_target', native_enum=False, length=32), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.Column('reviewer_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_by', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'declined', 'completed', name='assignment_status', native_enum=False, length=32), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decline_reason', sa.String(length=500), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], name=op.f('fk_review_assignments_assigned_by_users')),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], name=op.f('fk_review_assignments_reviewer_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_assignments')),
    sa.UniqueConstraint('target_type', 'target_id', 'reviewer_id', name='uq_assignment_target')
    )
    with op.batch_alter_table('review_assignments', schema=None) as batch_op:
        batch_op.create_index('ix_assignment_target', ['target_type', 'target_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_assignments_reviewer_id'), ['reviewer_id'], unique=False)

    op.create_table('review_comments',
    sa.Column('target_type', sa.Enum('claim', 'source_work', 'root_decision', 'report_version', name='review_target', native_enum=False, length=32), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('resolved_by', sa.Uuid(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('length(body) > 0', name=op.f('ck_review_comments_comment_body_required')),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_review_comments_author_id_users')),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], name=op.f('fk_review_comments_resolved_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_comments'))
    )
    with op.batch_alter_table('review_comments', schema=None) as batch_op:
        batch_op.create_index('ix_comment_target', ['target_type', 'target_id'], unique=False)

    op.create_table('corrections',
    sa.Column('target_type', sa.Enum('claim', 'source_work', 'root_decision', 'report_version', name='review_target', native_enum=False, length=32), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('before_snapshot', sa.Text(), nullable=False),
    sa.Column('after_snapshot', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('proposed', 'approved', 'applied', 'rejected', name='correction_status', native_enum=False, length=32), nullable=False),
    sa.Column('proposed_by', sa.Uuid(), nullable=False),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.String(length=500), nullable=True),
    sa.Column('dispute_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('length(description) > 0', name=op.f('ck_corrections_correction_desc_required')),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('fk_corrections_approved_by_users')),
    sa.ForeignKeyConstraint(['dispute_id'], ['disputes.id'], name=op.f('fk_corrections_dispute_id_disputes')),
    sa.ForeignKeyConstraint(['proposed_by'], ['users.id'], name=op.f('fk_corrections_proposed_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_corrections'))
    )
    with op.batch_alter_table('corrections', schema=None) as batch_op:
        batch_op.create_index('ix_correction_target', ['target_type', 'target_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('corrections', schema=None) as batch_op:
        batch_op.drop_index('ix_correction_target')

    op.drop_table('corrections')
    with op.batch_alter_table('review_comments', schema=None) as batch_op:
        batch_op.drop_index('ix_comment_target')

    op.drop_table('review_comments')
    with op.batch_alter_table('review_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_assignments_reviewer_id'))
        batch_op.drop_index('ix_assignment_target')

    op.drop_table('review_assignments')
    with op.batch_alter_table('disputes', schema=None) as batch_op:
        batch_op.drop_index('ix_dispute_target')

    op.drop_table('disputes')
    # ### end Alembic commands ###
